# Generated by Django 3.1.1 on 2020-11-06 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='gamemodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamemode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=600)),
                ('prize', models.IntegerField(default=0)),
                ('entryfee', models.IntegerField(default=0)),
                ('image', models.ImageField(default='default.png', upload_to='tournament_pics')),
                ('cover_image', models.ImageField(default='default.png', upload_to='tournament_cover_pics')),
                ('total_no_of_players', models.IntegerField()),
                ('date_of_tournament', models.DateTimeField()),
                ('Description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('tournament_youtube_url', embed_video.fields.EmbedVideoField(blank=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.game')),
                ('gametype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modmain.gamemodes')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modmain.platform')),
                ('winner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('In_game_name', models.CharField(default='', max_length=200)),
                ('Tournament_id', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='modmain.tournament')),
                ('User_id', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
