# Generated by Django 3.1.1 on 2020-11-06 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modmain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tournamentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gametype', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modmain.tournamenttype'),
        ),
    ]
