# Generated by Django 3.1.1 on 2020-11-06 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modmain', '0002_auto_20201106_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modmain.tournamenttype'),
        ),
    ]
