# Generated by Django 3.1.1 on 2020-11-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modmain', '0003_auto_20201106_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_icon', models.ImageField(default='default.png', upload_to='team_pics')),
            ],
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='total_no_of_players',
            new_name='total_no_of_players_or_team',
        ),
    ]
