# Generated by Django 3.1.1 on 2020-11-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modmain', '0005_auto_20201121_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team_memeber_details',
            old_name='varified',
            new_name='verified',
        ),
    ]
