# Generated by Django 3.1.1 on 2020-11-21 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modmain', '0006_auto_20201121_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_memeber_details',
            name='date_of_request',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
