# Generated by Django 3.1.1 on 2020-11-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modmain', '0007_team_memeber_details_date_of_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_player1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_player2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_player3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_player4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
