# Generated by Django 3.1.1 on 2020-11-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modmain', '0008_auto_20201121_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_player1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_player2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_player3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_player4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
