# Generated by Django 3.1.1 on 2020-11-30 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modmain', '0011_auto_20201121_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='date_of_creation',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
